// Sample Realistic Patient Data
export const patientData = [
  {
    id: 1,
    firstName: "Aarav",
    lastName: "Sharma",
    diagnosedWith: "Autism",
    dateOfBirth: "2015 May 10",
    gender: "Male",
    email: "aarav.sharma@example.com",
    phone: "+91 98765 43210",
    preferredLanguage: "Hindi",
    address: "45 MG Road, Mumbai, India",
    additionalNotes: "Requires occupational therapy and structured learning.",
  },
  {
    id: 2,
    firstName: "Emily",
    lastName: "Davis",
    diagnosedWith: "Down Syndrome",
    dateOfBirth: "2016 Jul 22",
    gender: "Female",
    email: "emily.davis@example.com",
    phone: "+1 (415) 234-5678",
    preferredLanguage: "English",
    address: "101 Elm Street, San Francisco, CA, USA",
    additionalNotes: "Receives speech therapy and special education support.",
  },
  {
    id: 3,
    firstName: "Rohan",
    lastName: "Mehta",
    diagnosedWith: "Autism",
    dateOfBirth: "2013 Nov 3",
    gender: "Male",
    email: "rohan.mehta@example.com",
    phone: "+91 90000 12345",
    preferredLanguage: "English",
    address: "23 Residency Road, Bangalore, India",
    additionalNotes:
      "Prefers non-verbal communication and sensory-friendly environments.",
  },
  {
    id: 4,
    firstName: "Sophia",
    lastName: "Martinez",
    diagnosedWith: "Other",
    dateOfBirth: "2017 Jan 15",
    gender: "Female",
    email: "sophia.martinez@example.com",
    phone: "+34 600 987 654",
    preferredLanguage: "Spanish",
    address: "Av. de la Constitución, Madrid, Spain",
    additionalNotes:
      "Mild developmental delay; attends early intervention programs.",
  },
  {
    id: 5,
    firstName: "Noah",
    lastName: "Anderson",
    diagnosedWith: "Down Syndrome",
    dateOfBirth: "2014 Sep 8",
    gender: "Male",
    email: "noah.anderson@example.com",
    phone: "+1 (212) 555-0198",
    preferredLanguage: "English",
    address: "789 Park Avenue, New York, NY, USA",
    additionalNotes:
      "Engages well in group therapy; enjoys music-based learning.",
  },
];
